package kama

import (
	"fmt"
	"regexp"
	"runtime"
	"strings"

	"reflect"

	"github.com/sanity-io/litter"
)

// vari represents a variable
type vari struct {
	Name      string
	Kind      reflect.Kind
	Signature []string
	Fields    []string
	Methods   []string
	Val       string
}

func newVari(i interface{}) vari {
	iType := reflect.TypeOf(i)
	if iType == nil {
		// TODO: maybe there is a way in reflect to diffrentiate the various types of nil
		return vari{
			Name:      "nil",
			Kind:      reflect.Ptr,
			Signature: []string{"nil"},
			Val:       dump(i)}
	}

	typeKind := getKind(i)
	typeName := getName(i)
	typeSig := getSignature(i)
	if typeName == "." {
		if typeKind == reflect.Func {
			typeName = runtime.FuncForPC(reflect.ValueOf(i).Pointer()).Name()
			if typeName == "" {
				typeName = "." + iType.Elem().Name()
			}
		} else {
			typeName = typeKind.String()
		}
	}

	var fields = getAllFields(i)
	var methods = trimMethods(getAllMethods(i))

	return vari{
		Name:      typeName,
		Kind:      typeKind,
		Signature: typeSig,
		Fields:    fields,
		Methods:   methods,
		Val:       dump(i),
	}

}

func (v vari) String() string {
	nLf := func(x []string) []string {
		var fm = []string{}
		if len(x) <= 0 {
			return fm
		}

		for _, c := range x {
			fm = append(fm, "\n\t"+c)
		}
		fm = append(fm, "\n\t")
		return fm
	}

	return fmt.Sprintf(
		`
[
NAME: %v
KIND: %v
SIGNATURE: %v
FIELDS: %v
METHODS: %v
SNIPPET: %s
]
`,
		v.Name,
		v.Kind,
		v.Signature,
		nLf(v.Fields),
		nLf(v.Methods),
		v.Val,
	)
}

func dump(i interface{}) string {
	sq := litter.Options{
		Compact:           false,
		StripPackageNames: true,
		HidePrivateFields: true,
		HideZeroValues:    false,
		FieldExclusions:   regexp.MustCompile(`^(XXX_.*)$`), // XXX_ is a prefix of fields generated by protoc-gen-go
		Separator:         " "}

	maxL := 120
	s := sq.Sdump(i)
	if len(s) <= maxL {
		maxL = len(s)
		return s[:maxL]
	}

	snipped := "\n...<snipped>.."
	if sq.Compact {
		snipped = " ...<snipped>.."
	}
	return s[:maxL] + snipped
}

func getName(i interface{}) string {
	iType := reflect.TypeOf(i)
	typeKind := iType.Kind()

	typeName := iType.PkgPath() + "." + iType.Name()
	if typeKind == reflect.Ptr {
		valueI := reflect.ValueOf(i).Elem()
		valueType := valueI.Type()
		typeName = valueType.PkgPath() + "." + valueType.Name()
	}

	return typeName
}

func getKind(i interface{}) reflect.Kind {
	iType := reflect.TypeOf(i)
	typeKind := iType.Kind()

	if typeKind != reflect.Ptr {
		return typeKind
	} else {
		// the passed in type maybe be a `*T` so lets find the kind of `T`
		valueI := reflect.ValueOf(i).Elem()
		valueType := valueI.Type()
		valueTypeKind := valueType.Kind()
		return valueTypeKind
	}
}

func getSignature(i interface{}) []string {
	iType := reflect.TypeOf(i)
	typeKind := iType.Kind()

	var allSignatures = []string{iType.String()}

	if typeKind == reflect.Ptr {
		// the passed in type maybe be a `*T` so lets find the signature of `T`
		valueI := reflect.ValueOf(i).Elem()
		vType := valueI.Type()
		sig := vType.String()
		allSignatures = append(allSignatures, sig)
	} else if typeKind == reflect.Struct {
		// the passed in type is a `T` so lets also find the signature of `*T`
		// NB: We are currently only allowing structs here. But we could expand to other types
		ptrOfT := reflect.PtrTo(iType)
		sig := ptrOfT.String()
		allSignatures = append(allSignatures, sig)
	}

	return allSignatures
}

// getFields finds all the fields(if any) of type `T` and `*T`
func getAllFields(i interface{}) []string {
	iType := reflect.TypeOf(i)
	typeKind := iType.Kind()

	var allFields = []string{}
	if typeKind == reflect.Ptr {
		// the passed in type maybe be a `*T struct{}` so lets also find methods of `T struct{}`
		valueI := reflect.ValueOf(i).Elem()
		allFields = getFields(valueI.Type())
	} else if typeKind == reflect.Struct {
		allFields = getFields(iType)
	}

	return allFields
}

// getFields finds all the fields(if any) of a type
func getFields(iType reflect.Type) []string {
	var fields = []string{}
	typeKind := iType.Kind()

	if typeKind == reflect.Struct {
		numFields := iType.NumField()
		for i := 0; i < numFields; i++ {
			f := iType.Field(i)
			if f.PkgPath != "" {
				// private field
				continue
			}
			fields = append(fields, f.Name+" "+f.Type.String())
		}
	}

	return fields
}

// getAllMethods finds all the methods of type `T` and `*T`
func getAllMethods(i interface{}) []string {
	iType := reflect.TypeOf(i)

	var allMethods = []string{}
	var methodsOfPassedInType = []string{}
	var methodsOfT = []string{}
	var methodsOfPointerT = []string{}

	methodsOfPassedInType = getMethods(iType)

	if iType.Kind() == reflect.Ptr {
		// the passed in type is a `*T` so lets also find methods of `T`
		valueI := reflect.ValueOf(i).Elem()
		methodsOfT = getMethods(valueI.Type())
	} else {
		// the passed in type is a `T` so lets also find methods of `*T`
		ptrOfT := reflect.PtrTo(iType)
		methodsOfPointerT = getMethods(ptrOfT)
	}

	allMethods = append(allMethods, methodsOfT...)
	allMethods = append(allMethods, methodsOfPointerT...)
	allMethods = append(allMethods, methodsOfPassedInType...)

	return allMethods
}

// getMethods finds all the methods of type.
func getMethods(iType reflect.Type) []string {
	var methods = []string{}
	numMethods := iType.NumMethod()
	for i := 0; i < numMethods; i++ {
		meth := iType.Method(i)
		if meth.PkgPath != "" {
			// private method
			continue
		}
		methName := meth.Name
		methSig := meth.Type.String() // type signature

		// TODO: maybe we should try and also add argument names if any.
		// currently the signature is displayed as;
		//   func(main.Foo, int, int) int
		// it would be cooler to display as;
		//   func(main.Foo, price int, commission int) int
		methods = append(methods, methName+" "+methSig)
	}

	return methods
}

// trimMethods removes any duplicated methods.
// if a method is applicable for both type `T` and `*T`, then `trimMethods` will
// just remove the one for `*T`
func trimMethods(methods []string) []string {

	// contains tells whether a contains x.
	contains := func(a []string, x string) bool {
		for _, n := range a {
			if x == n {
				return true
			}
		}
		return false
	}

	var trimmedMethods = []string{}
	var TmethNames []string

	// first add all methods for type `T`
	for _, meth := range methods {
		if !strings.Contains(meth, "*") {
			trimmedMethods = append(trimmedMethods, meth)
			methName := strings.Split(meth, " ")[0]
			TmethNames = append(TmethNames, methName)
		}
	}
	// then add methods for `*T` but only if they do not exist for `T`
	for _, meth := range methods {
		if strings.Contains(meth, "*") {
			methName := strings.Split(meth, " ")[0]
			if !contains(TmethNames, methName) {
				trimmedMethods = append(trimmedMethods, meth)
			}
		}
	}

	return trimmedMethods
}
